sudo: required
services: 
  - docker

before_install:
  - docker build -t tintuntint/docker-react -f Dockerfile.dev .

script:
    - docker run tintuntint/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-sample-1"
  env: "DockerSample1-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-519900252451"
  bucket_path: "docker-sample-1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
    


